# Copyright 2022 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

data_loader:
  train:
    dataset:
      type: Cifar10
      path: "" # Root directory of the Cifar10 dataset or inference image.
      split: "train"
      batch_size: 32 # Batch size of dataset.
      repeat_num: 1 # The repeat num of dataset.
      shuffle: True # Perform shuffle on the dataset.
      num_parallel_workers: 8 # Number of subprocess used to fetch the dataset in parallel.
      download: False # Whether to download the dataset.
    map:
      operations:
        - type: RandomCrop
          size: [32, 32]
          padding: [4, 4, 4, 4]
        - type: RandomHorizontalFlip
          prob: 0.5
        - type: Resize
          size: [224, 224]
        - type: Rescale
          rescale: 0.00392
          shift: 0.0
        - type: Normalize
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
        - type: HWC2CHW
  eval:
    dataset:
      type: Cifar10
      path: ""
      split: "test"
      batch_size: 32
      num_parallel_workers: 8
      download: False
    map:
      operations:
        - type: Resize
          size: [224, 224]
        - type: Rescale
          rescale: 0.00392
          shift: 0.0
        - type: Normalize
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
        - type: HWC2CHW
  infer:
    dataset:
      type: Cifar10
      path: ""
      split: "infer"
      batch_size: 1
    map:
      operations:
        - type: Resize
          size: [224, 224]
        - type: Rescale
          rescale: 0.00392
          shift: 0.0
        - type: Normalize
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
        - type: HWC2CHW
