# Copyright 2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

data_loader:
  train:
    mindrecord:
      type: Coco2MindRecord
      root: "/home/dataset/coco/train2017"
      ann_file: "/home/dataset/coco/annotations/instances_train2017.json"
      mindrecord_dir: "/home/dataset/coco_mr"
    dataset:
      type: MindDataset
      dataset_file: "/home/dataset/coco_mr/coco.mindrecord0"
      columns_list: ["image", "annotation"]
      num_shards: 1
      shard_id: 0
      num_parallel_workers: 8
      shuffle: True
    map:
      operations:
        - type: Format
          pad_max_number: 128
        - type: Decode
          decode_mode: C
        - type: ImgRgbToBgr
        - type: RandomExpand
          # mean: (0, 0, 0) # TODO
          to_rgb: True
          # ratio_range: (1, 4) # TODO
        - type: Rescale
          img_height: 768
          img_width: 1280
        - type: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_rgb: True
        - type: RandomFlip
          flip_ratio: 0.5
        - type: Transpose
          # perm: (2, 0, 1) # TODO
        - type: Collect
          output_orders: ["image", "image_shape", "bboxes", "labels", "valid_num"]
          output_type_dict:
            image: float32
            image_shape: float32
            bboxes: float32
            labels: int32
            valid_num: bool

      input_columns: ["image", "annotation"]
      output_columns: ["image", "image_shape", "bboxes", "labels", "valid_num"]
      column_order: ["image", "image_shape", "bboxes", "labels", "valid_num"]
      python_multiprocessing: False
    batch:
      batch_size: 2
      drop_remainder: True
  eval:
    dataset:
      type: MindDataset
      dataset_file: ["/home/lid/workspace/mindvision/mindvision/MindRecord_COCO_TRAIN/FasterRcnn_eval.mindrecord"]
      columns_list: ["image", "annotation"]
      num_shards: 1
      shard_id: 0
      num_parallel_workers: 8
      shuffle: False
    map:
      operations:
        - type: Format
          pad_max_number: 128
        - type: Decode
          decode_mode: C
        - type: ImgRgbToBgr
        - type: RescaleWithoutGT
          img_height: 768
          img_width: 1280
        - type: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_rgb: True
        - type: Transpose
          # perm: (2, 0, 1) # TODO
        - type: Collect
          output_orders: ["image", "image_shape", "bboxes", "labels", "valid_num"]
          # output_orders: ["image", "image_shape"]
          output_type_dict:
            image: float32
            image_shape: float32
            bboxes: float32
            labels: int32
            valid_num: bool

      input_columns: ["image", "annotation"]
      output_columns: ["image", "image_shape", "bboxes", "labels", "valid_num"]
      column_order: ["image", "image_shape", "bboxes", "labels", "valid_num"]
      python_multiprocessing: False
    batch:
      batch_size: 2
      drop_remainder: True
  infer:
    dataset:
      type: GeneratorDataset
      source:
        type: LoadImgFromFile
        img_file: "/home/linbert/mindvision/mindvision/detection/pictures"
      column_names: ["image", "image_id"]
      num_parallel_workers: 1
    map:
      operations:
        - type: Format
          is_infer: True
        - type: ImgRgbToBgr
        - type: RescaleWithoutGT
          img_height: 768
          img_width: 1280
        - type: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          to_rgb: True
        - type: Transpose
          # perm: (2, 0, 1) # TODO
        - type: Collect
          output_orders: ["image", "image_id", "image_shape"]
          output_type_dict:
            image: float32
            image_shape: float32
      input_columns: ["image", "image_id"]
      output_columns: ["image", "image_id", "image_shape"]
      column_order: ["image", "image_id", "image_shape"]
      num_parallel_workers: 1
    batch:
      batch_size: 2
      drop_remainder: True
    prefix: "id2pic.json"

  prefetch_size: 8
  thread_num: 0
  group_size: 1
