data_loader:
    train:
        mindrecord:
            type: WiderFace2MindRecord
            label_path: '/home/lijiaying/dataset/widerface/train/label.txt'
            mindrecord_dir: "/home/lijiaying/dataset/widerfacemr"
        dataset:
            type: MindDataset
            dataset_file: "/home/lijiaying/dataset/widerfacemr/widerface.mindrecord0"
            columns_list: ["image", "annotation"]
            num_shards: 1
            shard_id: 0
            num_parallel_workers: 8
            shuffle: True

        map:
             operations:
                - type: WiderFaceFormat
                - type: _Decode
                  decode_mode: C
                - type: ImgRgbToBgr 
                - type: RandomCropRetinaface
                  image_input_size: 840
                - type: RetinafaceBboxPreprocess
                  match_thresh: 0.35
                  variance: [0.1, 0.2]
                  image_size: 840
                  anchor: [[16, 32], [64, 128], [256, 512]]
                  step: [8, 16, 32]
                  clip: False
                - type: _Normalize
                  mean: [123.675, 116.28, 103.53]
                  std: [1.000, 1.000, 1.000]
                  to_rgb: True  
                - type: Transpose
                - type: Collect
                  output_orders: ["image", "truths", "conf", "landm"]
                  output_type_dict:
                      image: float32
                      truths: float32
                      conf: float32
                      landm: float32
             input_columns: ["image", "annotation"]
             output_columns: ["image", "truths", "conf", "landm"]
             column_order: ["image", "truths", "conf", "landm"]
             python_multiprocessing: True
        batch:
            batch_size: 8
            drop_remainder: True
    
    eval:
        mindrecord:
            type: WiderFace2MindRecord
            label_path: '/home/lijiaying/dataset/widerface/val/label.txt'
            mindrecord_dir: "/home/lijiaying/dataset/widerfacemr_eval"
            eval_imageid_file: "eval_imageid_file.json"
            is_training: False
        dataset:
            type: MindDataset
            dataset_file: "/home/lijiaying/dataset/widerfacemr_eval/widerface.mindrecord"
            columns_list: ["image", "annotation"]
            num_shards: 1
            shard_id: 0
            num_parallel_workers: 8
            shuffle: False
        map:
            operations:
                - type: EvalFormat
                - type: _Decode
                  decode_mode: C
                - type: ImgRgbToBgr
                - type: EqualProportionResize
                  target_size: 1600
                  max_size: 2176
                - type: RetinafaceBboxPreprocess
                  image_size: 2176
                  anchor: [ [ 16, 32 ], [ 64, 128 ], [ 256, 512 ] ]
                  step: [ 8, 16, 32 ]
                  clip: False
                - type: _Normalize
                  std: [1.000, 1.000, 1.000]
                - type: Transpose
                - type: Collect
                  output_orders: ["image", "resize", "scale", "priors", "image_id"]
                  output_type_dict:
                      image: float32
                      scale: float32
                      resize: float32
                      priors: float32
                      image_id: int32
            input_columns: ["image", "annotation"]
            output_columns: ["image", "resize", "scale", "priors", "image_id"]
            column_order: ["image", "resize", "scale", "priors", "image_id"]
            python_multiprocessing: False
        batch:
            batch_size: 1
            drop_remainder: True

    prefetch_size: 8
    thread_num: 0
    group_size: 1
