# Copyright 2021 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================
base_config: ['../base/datasets/centerface_dataset_mindrecord.yaml',
              '../base/models/centerface_mobilev2.yaml',
              '../base/schedules/schedule_centerface.yaml']
train:
  load_path: ""
  backbone_path: "model_ckpt/mobilenetv2_ascend_v120_imagenet2012_official_cv_bs256_acc71.ckpt"
  filter_weight: False
  max_epoch: 140
  ckpt_interval: -1
  rank_save_ckpt_flag: 1
  is_distributed: True
  rank: 0
  run_eval: False
  save_best_ckpt: True
  ckpt_path: 'outputs_train'
  context:
    mode: 0 #0--Graph Mode; 1--Pynative Mode
    enable_auto_mixed_precision: True
    device_target: "Ascend"
    save_graphs: False
    device_id: 0

  need_profiler: 0
  profiler:
    is_detail: True
    is_show_op_path: True
  parallel:
    parallel_mode: "data_parallel"
    gradients_mean: True
    device_num: 1
  ckpt:
    max_num: 10
  dataset_sink_mode: True

eval:
  ckpt_path: ""
  is_distributed: False
  rank: 0
  detection_engine:
    type: CenterfaceDetectionEngine
    num_classes: 1
    nms: 1
    test_scales: [0.999,]
    k_num: 200
    iou_thresh: 0.4
    reg_offset: True
    ground_truth_path: '/home/iscas_zhang2/centerfacemr/ground_truth' #WiderFace数据集ground_truth路径
    eval_imageid_file: 'mindrecord_eval.json'
    save_path: "eval/"
  context:
    mode: 0 #0--Graph Mode; 1--Pynative Mode
    device_target: "Ascend"
    save_graphs: False
    device_id: 0
  test_batch_size: 1

learning_rate: # centerface
  lr_scheduler: "multistep"
  lr: 0.004 # 4e-3
  lr_epochs: [90,120]
  lr_gamma: 0.1
  max_epoch: 140
  warmup_epochs: 0

optimizer: # centerface
  type: Adam
  weight_decay: 0.0000  # 单卡:0.0005，八卡:0.0000
  loss_scale: 1024

train_wrapper:
  type: TrainingWrapper
