# Copyright 2021 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

base_config: ['../base/datasets/retinanet_dataset.yaml',
              '../base/models/retinanet_r50_fpn.yaml',
              '../base/schedules/schedule1x.yaml',
              '../base/base.yaml']
model:
  type: RetinaNet
  backbone:
    type: ResNet
    depth: 50
    strides: [1, 2, 2, 2]
    in_channels: [64, 256, 512, 1024]
    out_channels: [256, 512, 1024, 2048]
    weights_update: False

train:
  backbone_path: "./resnet50_backbone.ckpt"
  max_epoch: 500
  ckpt_path: "outputs/"
  network_data_type:
    backbone: float16
    neck: float16
eval:
  ckpt_path: ""
  detection_engine:
    type: RetinaDetectionEngine
    ann_file: "/home/iscas_zhang1/data/coco/annotations/instances_val2017.json"
    test_batch_size: 1
    num_classes: 81
    min_score: 0.1
    nms_thershold: 0.6
    max_boxes: 100

learning_rate: # RetinaNet
  lr_scheduler: "multi_warmup_epochs_lr"
  lr: 0.1
  lr_init: 1e-6
  lr_end_rate: 5e-3
  warmup_epochs: [2, 5, 23, 60, 160]
  max_epoch: 500

optimizer: # RetinaNet
  type: Momentum
  momentum: 0.9
  weight_decay: 1.5e-4
  loss_scale: 1024
